### PR TITLE
Make iScale a double to allow scaling when screen is smaller than graph

### PR DESCRIPTION
**Pull request by ghost**
On my tiny 1080p screen the window got size 0x0.

Change-Id: I15dd10cb77685ae5e6b790c440eced88c89de789

### CODE REVIEW

**Review by kajohansson — COMMENTED** [review]
I see the perceived problem, but the correct solution is to instead cap scale at integer 1. The _actual_ problem is that the rendered graph size is larger than the screen. This should never happen in a real world use case where graph size always is less than or equal to window size. So in this case, the change should be to cap graph_width and graph_height to something smaller than the screen and then calculate the integer scaling factor.

**Comment by ghost** [comment]
That would make more sense yes. Seems like you have to init the SDL before setting the graph dSamplesPerPixel etc. then.

**Comment by kajohansson** [comment]
Fixed on master now! Regarding dSamplesPerPixel: The API to the graph renderer actually uses samplepos for left and right edges rather than samplesPerPixel. So it's just the demo app that still uses samplesPerPixel as a way to maintain scale. A real app may keep zoom settings in any way it wants. It makes sense to _not_ have it relative actual pixel size of the window...

**Comment by ghost** [comment]
Great!

**Pull request closed without merging**
